version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./docker-data:/data/db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8090:8080
